spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/spend_sage'
    username: spend_sage
    password: spend_sage
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
      format-sql: true
    database: postgresql

  application:
    name: spend-sage
    security:
      jwt:
        secret: a592c622d697adfabafb71d7879a5ce91290f57b38074543b22e94854575405b
        expiration: 86400000 # 1 day
        refresh-token:
          expiration: 604800000 # 7 days

  mvc:
    format:
      date: dd-MM-yyyy
      time: HH:mm:ss
      date-time: dd-MM-yyyy HH:mm:ss
